{% set name = "autoesda" %}
{% set version = "0.0.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f7bd3a57750364a6fc970209b6ebf3049017e20ed57261d00d357aa0074a4561

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - esda
    - geopandas ==0.8.1
    - libpysal ==4.4.0
    - matplotlib ==3.4.2
    - pysal ==2.3.0
    - python >={{ python_min }}
    - seaborn ==0.11.2
    - splot >=1.1.4

test:
  requires:
    - python {{ python_min }}
  imports:
    - autoesda

about:
  home: https://github.com/NicholasDeKock/autoesda
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A Python package that automates the exploratory spatial data analysis (ESDA) process by summarizing the results in an HTML report
  doc_url: https://nicholasdekock.github.io/autoesda/
  dev_url: https://github.com/NicholasDeKock/autoesda

extra:
  recipe-maintainers:
    - NicholasDeKock
